name: Publish npm package
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@${{ github.actor }}'
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - name: Install dependencies
      run: pnpm i
    - name: Publish packages
      run: pnpm run publish-packages
